[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -I../../protocol/include
  -I../../library/include

build_src_filter =
  +<*>
  +<../../../protocol/src/codec.cpp>
  +<../../../library/src/stream_parser.cpp>
  +<../../../library/src/node.cpp>
  +<../../../library/src/lighting.cpp>
  +<../../../library/src/lighting_server.cpp>
  +<../../../library/src/lighting_controller.cpp>
