#include <chrono>
#include <cstdint>
#include <iostream>
#include <poll.h>
#include <string>
#include "bike/motorcycle_computer.hpp"
#include "posix_serial_transport.hpp"
namespace {
std::uint32_t monotonic_ms(){using namespace std::chrono;return static_cast<std::uint32_t>(duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count());}
const char* online_text(const bike::NodeStatus*s){if(!s||!s->discovered)return"UNKNOWN";return s->online?"ONLINE":"OFFLINE";} const char* on_off(bool v){return v?"ON":"OFF";}
const char* health_text(bike::NodeHealth h){switch(h){case bike::NodeHealth::Unknown:return"UNKNOWN";case bike::NodeHealth::Online:return"ONLINE";case bike::NodeHealth::Degraded:return"DEGRADED";case bike::NodeHealth::Offline:return"OFFLINE";case bike::NodeHealth::Incompatible:return"INCOMPATIBLE";}return"UNKNOWN";}
const char* security_mode_text(bike::SecurityMode m){switch(m){case bike::SecurityMode::Unlocked:return"UNLOCKED";case bike::SecurityMode::Locked:return"LOCKED";case bike::SecurityMode::Alarm:return"ALARM";case bike::SecurityMode::LockPending:return"LOCK_PENDING";}return"UNKNOWN";}
const char* device_class_text(bike::DeviceClass c){switch(c){case bike::DeviceClass::MainComputer:return"MAIN_COMPUTER";case bike::DeviceClass::DiagnosticComputer:return"DIAGNOSTIC_COMPUTER";case bike::DeviceClass::NetworkController:return"NETWORK_CONTROLLER";case bike::DeviceClass::LightingController:return"LIGHTING_CONTROLLER";case bike::DeviceClass::SecurityController:return"SECURITY_CONTROLLER";}return"UNKNOWN";}
void print_inventory(const bike::NetworkSupervisor&s){std::cout<<"device-inventory required-fault="<<(s.required_node_fault()?"YES":"NO")<<":\n";for(const auto&n:s.nodes()){if(!n.discovered)continue;std::cout<<"  node=0x"<<std::hex<<static_cast<unsigned>(bike::to_u8(n.address))<<std::dec<<" health="<<health_text(n.health)<<" required="<<(n.required?"YES":"NO");if(!n.identity_valid){std::cout<<" identity=UNKNOWN\n";continue;}std::cout<<" class="<<device_class_text(n.device_class)<<" fw="<<unsigned(n.firmware_major)<<'.'<<unsigned(n.firmware_minor)<<'.'<<unsigned(n.firmware_patch)<<" protocol="<<unsigned(n.protocol_version)<<(n.protocol_compatible?"(OK)":"(INCOMPATIBLE)")<<" hw="<<unsigned(n.hardware_revision)<<" uptime_ms="<<n.uptime_ms<<" reboots="<<n.reboot_count<<" capabilities=0x"<<std::hex<<n.capabilities<<std::dec<<" faults="<<n.fault_count<<'\n';}}
void print_status(const bike::MotorcycleSnapshot&s){std::cout<<"northbridge="<<online_text(s.northbridge_node)<<" lighting-node="<<online_text(s.lighting_node)<<" security-node="<<online_text(s.security_node)<<" tx_failures="<<s.tx_failures<<" rx_drops="<<s.rx_drops<<'\n';if(s.northbridge.valid)std::cout<<"northbridge-network: forwarded="<<s.northbridge.forwarded_packets<<" dropped="<<s.northbridge.dropped_packets<<" route-movements="<<s.northbridge.route_movement_events<<" topology-faults="<<s.northbridge.topology_fault_events<<'\n';if(s.lighting.valid)std::cout<<"lighting: left="<<on_off(s.lighting.left_indicator)<<" right="<<on_off(s.lighting.right_indicator)<<" brake="<<on_off(s.lighting.brake_bright)<<" high="<<on_off(s.lighting.high_beam)<<'\n';if(s.security.valid)std::cout<<"security: mode="<<security_mode_text(s.security.mode)<<" inhibit="<<on_off(s.security.start_inhibit)<<" alarm="<<on_off(s.security.alarm_active)<<" engine-running="<<on_off(s.security.engine_running)<<'\n';}
bool handle_command(const std::string&l,bike::MotorcycleComputer&c,std::uint32_t now){if(l=="quit"||l=="exit")return false;if(l=="status")print_status(c.snapshot());else if(l=="inventory")print_inventory(c.supervisor());else if(l=="left on")c.lighting().set_left_indicator(true,now);else if(l=="left off")c.lighting().set_left_indicator(false,now);else if(l=="right on")c.lighting().set_right_indicator(true,now);else if(l=="right off")c.lighting().set_right_indicator(false,now);else if(l=="brake on")c.lighting().set_brake_bright(true,now);else if(l=="brake off")c.lighting().set_brake_bright(false,now);else if(l=="high on")c.lighting().set_high_beam(true,now);else if(l=="high off")c.lighting().set_high_beam(false,now);else if(l=="lock")c.security().lock(now);else if(l=="unlock")c.security().unlock(now);else if(l=="silence")c.security().silence_alarm(now);else if(l=="refresh")c.request_all_states(now);else if(!l.empty())std::cout<<"Unknown command\n";return true;}
}
int main(int argc,char**argv){const std::string device=argc>1?argv[1]:"/dev/serial0";PosixSerialTransport transport;if(!transport.open_device(device,115200)){std::cerr<<"Failed to open northbridge serial device: "<<device<<'\n';return 1;}bike::BikeNode node(bike::NodeAddress::MainComputer,transport);bike::MotorcycleComputer computer(node);computer.begin(monotonic_ms());std::cout<<"Motorcycle computer connected on "<<device<<"\nCommands: status, inventory, refresh, left on|off, right on|off, brake on|off, high on|off, lock, unlock, silence, quit\n> "<<std::flush;pollfd p{};p.fd=0;p.events=POLLIN;std::string line;bool running=true;while(running){computer.service(monotonic_ms());int ready=::poll(&p,1,10);if(ready<0)break;if(ready&&p.revents&POLLIN){if(!std::getline(std::cin,line))break;running=handle_command(line,computer,monotonic_ms());if(running)std::cout<<"> "<<std::flush;}}return 0;}
