#include <array>
#include <chrono>
#include <cstdint>
#include <deque>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <poll.h>
#include <sstream>
#include <string>
#include "bike/lighting_diagnostics.hpp"
#include "bike/node.hpp"
#include "bike/security.hpp"
#include "bike/supervisor.hpp"
#include "posix_serial_transport.hpp"
namespace {
struct Event{std::uint32_t time_ms;bike::NodeAddress source;bike::MessageType type;std::string text;};std::deque<Event> history;constexpr std::size_t kHistoryLimit=250;std::ofstream logfile;bool monitor=true;bool filter_node_enabled=false;bike::NodeAddress filter_node=bike::NodeAddress::Broadcast;
struct Probe{bool active{false};bike::NodeAddress target{bike::NodeAddress::Broadcast};std::uint32_t started{0};};Probe probe;
enum class TestResult{Pending,Pass,Warn,Fail};struct TestItem{bike::NodeAddress node;bike::MessageType request;bike::MessageType response;TestResult result{TestResult::Pending};std::uint32_t started{0};std::uint32_t elapsed{0};std::string detail;};
struct SelfTest{bool active{false};std::size_t index{0};std::uint32_t started{0};std::array<TestItem,3> items{{{bike::NodeAddress::Northbridge,bike::MessageType::Diagnostic,bike::MessageType::Diagnostic},{bike::NodeAddress::Lighting,bike::MessageType::GetState,bike::MessageType::StateUpdate},{bike::NodeAddress::Security,bike::MessageType::GetState,bike::MessageType::SecurityState}}};};SelfTest selftest;
std::uint32_t now_ms(){using namespace std::chrono;return static_cast<std::uint32_t>(duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count());}
const char* node_name(bike::NodeAddress a){switch(a){case bike::NodeAddress::MainComputer:return"MAIN";case bike::NodeAddress::DiagnosticComputer:return"DIAG";case bike::NodeAddress::Northbridge:return"NORTHBRIDGE";case bike::NodeAddress::Lighting:return"LIGHTING";case bike::NodeAddress::Security:return"SECURITY";case bike::NodeAddress::Broadcast:return"BROADCAST";}return"UNKNOWN";}
const char* type_name(bike::MessageType t){switch(t){case bike::MessageType::Heartbeat:return"HEARTBEAT";case bike::MessageType::Ack:return"ACK";case bike::MessageType::Nack:return"NACK";case bike::MessageType::GetState:return"GET_STATE";case bike::MessageType::StateUpdate:return"STATE_UPDATE";case bike::MessageType::SetOutput:return"SET_OUTPUT";case bike::MessageType::InputEvent:return"INPUT_EVENT";case bike::MessageType::LightingDiagnostic:return"LIGHTING_DIAGNOSTIC";case bike::MessageType::Fault:return"FAULT";case bike::MessageType::FaultClear:return"FAULT_CLEAR";case bike::MessageType::DeviceInfo:return"DEVICE_INFO";case bike::MessageType::DeviceDiscovery:return"DEVICE_DISCOVERY";case bike::MessageType::Diagnostic:return"DIAGNOSTIC";case bike::MessageType::SecurityCommand:return"SECURITY_COMMAND";case bike::MessageType::SecurityState:return"SECURITY_STATE";case bike::MessageType::SecurityEvent:return"SECURITY_EVENT";default:return"OTHER";}}
const char* health(bike::NodeHealth h){switch(h){case bike::NodeHealth::Unknown:return"UNKNOWN";case bike::NodeHealth::Online:return"ONLINE";case bike::NodeHealth::Degraded:return"DEGRADED";case bike::NodeHealth::Offline:return"OFFLINE";case bike::NodeHealth::Incompatible:return"INCOMPATIBLE";}return"?";}
std::uint32_t u32(const std::uint8_t*p){return(std::uint32_t(p[0])<<24)|(std::uint32_t(p[1])<<16)|(std::uint32_t(p[2])<<8)|p[3];}
std::string hex_payload(const bike::Packet&p){std::ostringstream o;for(std::uint16_t i=0;i<p.length;++i){if(i)o<<' ';o<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(p.payload[i]);}return o.str();}
std::string decode(const bike::Packet&p){std::ostringstream o;o<<type_name(p.type);if(p.type==bike::MessageType::SecurityState&&p.length>=6)o<<" mode="<<unsigned(p.payload[0])<<" inhibit="<<unsigned(p.payload[1])<<" alarm="<<unsigned(p.payload[2])<<" warning="<<unsigned(p.payload[3])<<" trigger="<<unsigned(p.payload[4])<<" engine="<<unsigned(p.payload[5]);else if(p.type==bike::MessageType::StateUpdate&&p.length>=8)o<<" left="<<unsigned(p.payload[1])<<" right="<<unsigned(p.payload[3])<<" brake="<<unsigned(p.payload[5])<<" high="<<unsigned(p.payload[7]);else if(p.type==bike::MessageType::Diagnostic&&p.source==bike::NodeAddress::Northbridge&&p.length>=18)o<<" ports="<<unsigned(p.payload[1])<<" forwarded="<<u32(&p.payload[2])<<" dropped="<<u32(&p.payload[6])<<" route-movements="<<u32(&p.payload[10])<<" topology-faults="<<u32(&p.payload[14]);else if(p.length)o<<" payload=["<<hex_payload(p)<<']';return o.str();}
void remember(std::uint32_t t,const bike::Packet&p,const std::string&s){history.push_back({t,p.source,p.type,s});while(history.size()>kHistoryLimit)history.pop_front();if(logfile){logfile<<t<<','<<node_name(p.source)<<','<<node_name(p.destination)<<','<<type_name(p.type)<<",\""<<s<<"\"\n";logfile.flush();}}
bool send_request(bike::BikeNode&n,bike::NodeAddress dst,bike::MessageType type,std::uint32_t now){bike::Packet p{};p.destination=dst;p.type=type;return n.send(p,now,false);}
void finish_selftest(){std::cout<<"SELF-TEST REPORT\n";unsigned pass=0,warn=0,fail=0;for(const auto&i:selftest.items){const char*r=i.result==TestResult::Pass?"PASS":i.result==TestResult::Warn?"WARN":"FAIL";std::cout<<"  "<<node_name(i.node)<<": "<<r<<" "<<i.elapsed<<"ms "<<i.detail<<'\n';if(i.result==TestResult::Pass)++pass;else if(i.result==TestResult::Warn)++warn;else ++fail;}std::cout<<"SUMMARY pass="<<pass<<" warn="<<warn<<" fail="<<fail<<" total="<<std::uint32_t(now_ms()-selftest.started)<<"ms\n";selftest.active=false;}
void start_next_test(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){while(selftest.index<selftest.items.size()){auto&i=selftest.items[selftest.index];const auto*st=s.status(i.node);if(!st||!st->online){i.result=TestResult::Fail;i.detail="offline";++selftest.index;continue;}if(st->health==bike::NodeHealth::Incompatible){i.result=TestResult::Fail;i.detail="protocol incompatible";++selftest.index;continue;}i.started=now;if(!send_request(n,i.node,i.request,now)){i.result=TestResult::Fail;i.detail="request send failed";++selftest.index;continue;}std::cout<<"SELF-TEST querying "<<node_name(i.node)<<"...\n";return;}finish_selftest();}
void begin_selftest(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(selftest.active){std::cout<<"SELF-TEST already running\n";return;}selftest=SelfTest{};selftest.active=true;selftest.started=now;std::cout<<"SELF-TEST START\n";start_next_test(n,s,now);}
void observe_selftest(const bike::Packet&p,bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(!selftest.active||selftest.index>=selftest.items.size())return;auto&i=selftest.items[selftest.index];if(p.source!=i.node||p.type!=i.response)return;i.elapsed=std::uint32_t(now-i.started);bool valid=true;std::string detail="response valid";if(i.node==bike::NodeAddress::Northbridge){valid=p.length>=18;if(valid&&u32(&p.payload[6])>0){i.result=TestResult::Warn;detail="routing active, dropped packets recorded";}}else if(i.node==bike::NodeAddress::Lighting){valid=p.length>=8;if(valid)detail="lighting state received";}else if(i.node==bike::NodeAddress::Security){valid=p.length>=6;if(valid)detail="security state received";}if(!valid){i.result=TestResult::Fail;i.detail="malformed response";}else if(i.result!=TestResult::Warn){const auto*st=s.status(i.node);i.result=(st&&st->health==bike::NodeHealth::Degraded)?TestResult::Warn:TestResult::Pass;i.detail=(i.result==TestResult::Warn)?"response valid, node degraded":detail;}else i.detail=detail;++selftest.index;start_next_test(n,s,now);}
void service_selftest(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(!selftest.active||selftest.index>=selftest.items.size())return;auto&i=selftest.items[selftest.index];if(std::uint32_t(now-i.started)<=1000)return;i.result=TestResult::Fail;i.elapsed=std::uint32_t(now-i.started);i.detail="response timeout";++selftest.index;start_next_test(n,s,now);}
void ping(bike::BikeNode&n,bike::NodeAddress dst,std::uint32_t now){if(send_request(n,dst,bike::MessageType::Heartbeat,now)){probe={true,dst,now};std::cout<<"PING "<<node_name(dst)<<" sent\n";}}
bool parse_node(const std::string&s,bike::NodeAddress&a){if(s=="northbridge")a=bike::NodeAddress::Northbridge;else if(s=="lighting")a=bike::NodeAddress::Lighting;else if(s=="security")a=bike::NodeAddress::Security;else return false;return true;}
void inventory(const bike::NetworkSupervisor&s){for(const auto&n:s.nodes())if(n.discovered)std::cout<<node_name(n.address)<<" health="<<health(n.health)<<" faults="<<n.fault_count<<" reboots="<<n.reboot_count<<'\n';}
}
int main(int argc,char**argv){std::string dev=argc>1?argv[1]:"/dev/serial0";PosixSerialTransport transport;if(!transport.open_device(dev,115200)){std::cerr<<"Unable to open "<<dev<<'\n';return 1;}logfile.open("motorcycle-diagnostics.csv",std::ios::app);bike::BikeNode node(bike::NodeAddress::DiagnosticComputer,transport);bike::NetworkSupervisor supervisor(node);supervisor.send_discovery(now_ms());std::cout<<"Motorcycle diagnostics on "<<dev<<"\nCommands: scan, inventory, state lighting|security, diag northbridge, ping <node>, selftest, monitor on|off, quit\n> "<<std::flush;pollfd input{0,POLLIN,0};std::string line;bool running=true;while(running){auto now=now_ms();bike::Packet p{};while(node.poll(p,now)){supervisor.observe(p,now);auto text=decode(p);remember(now,p,text);observe_selftest(p,node,supervisor,now);if(probe.active&&p.source==probe.target&&p.type==bike::MessageType::Heartbeat){std::cout<<"PING "<<node_name(probe.target)<<" reply "<<std::uint32_t(now-probe.started)<<"ms\n";probe.active=false;}if(monitor)std::cout<<'['<<now<<"] "<<node_name(p.source)<<" -> "<<node_name(p.destination)<<' '<<text<<'\n';}service_selftest(node,supervisor,now);if(probe.active&&std::uint32_t(now-probe.started)>1000){std::cout<<"PING "<<node_name(probe.target)<<" TIMEOUT\n";probe.active=false;}supervisor.service(now);node.service(now);int ready=::poll(&input,1,10);if(ready>0&&(input.revents&POLLIN)){if(!std::getline(std::cin,line))break;if(line=="quit"||line=="exit")running=false;else if(line=="scan")supervisor.send_discovery(now);else if(line=="inventory")inventory(supervisor);else if(line=="selftest")begin_selftest(node,supervisor,now);else if(line=="monitor on")monitor=true;else if(line=="monitor off")monitor=false;else if(line=="diag northbridge")send_request(node,bike::NodeAddress::Northbridge,bike::MessageType::Diagnostic,now);else if(line=="state lighting")send_request(node,bike::NodeAddress::Lighting,bike::MessageType::GetState,now);else if(line=="state security")send_request(node,bike::NodeAddress::Security,bike::MessageType::GetState,now);else if(line.rfind("ping ",0)==0){bike::NodeAddress a;if(parse_node(line.substr(5),a))ping(node,a,now);else std::cout<<"Unknown node\n";}else if(!line.empty())std::cout<<"Unknown command\n";if(running)std::cout<<"> "<<std::flush;}}return 0;}
