#include <array>
#include <chrono>
#include <cstdint>
#include <deque>
#include <iomanip>
#include <iostream>
#include <poll.h>
#include <sstream>
#include <string>
#include "bike/node.hpp"
#include "bike/supervisor.hpp"
#include "posix_serial_transport.hpp"
namespace {
struct Event { std::uint32_t time_ms; bike::NodeAddress source; bike::MessageType type; std::string text; };
std::deque<Event> history; constexpr std::size_t kHistoryLimit=100;
std::uint32_t now_ms(){using namespace std::chrono;return static_cast<std::uint32_t>(duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count());}
const char* node_name(bike::NodeAddress a){switch(a){case bike::NodeAddress::MainComputer:return"MAIN";case bike::NodeAddress::DiagnosticComputer:return"DIAG";case bike::NodeAddress::Northbridge:return"NORTHBRIDGE";case bike::NodeAddress::Lighting:return"LIGHTING";case bike::NodeAddress::Security:return"SECURITY";case bike::NodeAddress::Broadcast:return"BROADCAST";}return"UNKNOWN";}
const char* type_name(bike::MessageType t){switch(t){case bike::MessageType::Heartbeat:return"HEARTBEAT";case bike::MessageType::Ack:return"ACK";case bike::MessageType::Nack:return"NACK";case bike::MessageType::GetState:return"GET_STATE";case bike::MessageType::StateUpdate:return"STATE_UPDATE";case bike::MessageType::SetOutput:return"SET_OUTPUT";case bike::MessageType::InputEvent:return"INPUT_EVENT";case bike::MessageType::LightingDiagnostic:return"LIGHTING_DIAGNOSTIC";case bike::MessageType::ConfigRead:return"CONFIG_READ";case bike::MessageType::ConfigWrite:return"CONFIG_WRITE";case bike::MessageType::Fault:return"FAULT";case bike::MessageType::FaultClear:return"FAULT_CLEAR";case bike::MessageType::DeviceInfo:return"DEVICE_INFO";case bike::MessageType::DeviceDiscovery:return"DEVICE_DISCOVERY";case bike::MessageType::Diagnostic:return"DIAGNOSTIC";case bike::MessageType::SecurityCommand:return"SECURITY_COMMAND";case bike::MessageType::SecurityState:return"SECURITY_STATE";case bike::MessageType::SecurityEvent:return"SECURITY_EVENT";case bike::MessageType::AuthRequest:return"AUTH_REQUEST";case bike::MessageType::AuthResult:return"AUTH_RESULT";case bike::MessageType::FobPresent:return"FOB_PRESENT";}return"UNKNOWN";}
const char* health(bike::NodeHealth h){switch(h){case bike::NodeHealth::Unknown:return"UNKNOWN";case bike::NodeHealth::Online:return"ONLINE";case bike::NodeHealth::Degraded:return"DEGRADED";case bike::NodeHealth::Offline:return"OFFLINE";case bike::NodeHealth::Incompatible:return"INCOMPATIBLE";}return"?";}
std::string payload_hex(const bike::Packet&p){std::ostringstream o;for(std::uint16_t i=0;i<p.length;++i){if(i)o<<' ';o<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(p.payload[i]);}return o.str();}
std::string decode(const bike::Packet&p){std::ostringstream o;o<<type_name(p.type);if(p.type==bike::MessageType::SecurityState&&p.length>=5)o<<" mode="<<unsigned(p.payload[0])<<" inhibit="<<unsigned(p.payload[1])<<" alarm="<<unsigned(p.payload[2])<<" engine="<<unsigned(p.payload[4]);else if(p.type==bike::MessageType::StateUpdate&&p.length>=4)o<<" left="<<unsigned(p.payload[0])<<" right="<<unsigned(p.payload[1])<<" brake="<<unsigned(p.payload[2])<<" high="<<unsigned(p.payload[3]);else if((p.type==bike::MessageType::Fault||p.type==bike::MessageType::FaultClear)&&p.length)o<<" payload=["<<payload_hex(p)<<']';else if(p.type==bike::MessageType::DeviceInfo&&p.length>=8)o<<" schema="<<unsigned(p.payload[0])<<" class="<<unsigned(p.payload[2])<<" protocol="<<unsigned(p.payload[3])<<" fw="<<unsigned(p.payload[4])<<'.'<<unsigned(p.payload[5])<<'.'<<unsigned(p.payload[6])<<" hw="<<unsigned(p.payload[7]);else if(p.length)o<<" payload=["<<payload_hex(p)<<']';return o.str();}
void remember(std::uint32_t t,const bike::Packet&p,const std::string&text){history.push_back({t,p.source,p.type,text});while(history.size()>kHistoryLimit)history.pop_front();}
void packet_line(std::uint32_t t,const bike::Packet&p){std::cout<<'['<<t<<"] "<<node_name(p.source)<<" -> "<<node_name(p.destination)<<' '<<decode(p)<<" seq="<<p.sequence<<" len="<<p.length<<" flags=0x"<<std::hex<<unsigned(p.flags)<<std::dec<<'\n';}
void inventory(const bike::NetworkSupervisor&s){std::cout<<"\nNETWORK INVENTORY required-fault="<<(s.required_node_fault()?"YES":"NO")<<'\n';for(const auto&n:s.nodes()){if(!n.discovered)continue;std::cout<<node_name(n.address)<<"(0x"<<std::hex<<unsigned(bike::to_u8(n.address))<<std::dec<<") "<<health(n.health)<<" required="<<(n.required?"yes":"no");if(n.identity_valid)std::cout<<" fw="<<unsigned(n.firmware_major)<<'.'<<unsigned(n.firmware_minor)<<'.'<<unsigned(n.firmware_patch)<<" proto="<<unsigned(n.protocol_version)<<" uptime="<<n.uptime_ms<<"ms reboots="<<n.reboot_count<<" faults="<<n.fault_count;else std::cout<<" identity=pending";std::cout<<'\n';}}
void print_history(bool faults_only){for(const auto&e:history){if(faults_only&&e.type!=bike::MessageType::Fault&&e.type!=bike::MessageType::FaultClear)continue;std::cout<<'['<<e.time_ms<<"] "<<node_name(e.source)<<' '<<e.text<<'\n';}}
}
int main(int argc,char**argv){const std::string dev=argc>1?argv[1]:"/dev/serial0";PosixSerialTransport transport;if(!transport.open_device(dev,115200)){std::cerr<<"Unable to open "<<dev<<'\n';return 1;}bike::BikeNode node(bike::NodeAddress::DiagnosticComputer,transport);bike::NetworkSupervisor supervisor(node);supervisor.send_discovery(now_ms());std::cout<<"Motorcycle diagnostic computer on "<<dev<<"\nCommands: scan, inventory, monitor on|off, events, faults, clear, quit\n> "<<std::flush;bool running=true,monitor=true;pollfd input{};input.fd=0;input.events=POLLIN;std::string line;while(running){const auto now=now_ms();bike::Packet packet{};while(node.poll(packet,now)){supervisor.observe(packet,now);const auto text=decode(packet);remember(now,packet,text);if(monitor)packet_line(now,packet);}supervisor.service(now);node.service(now);int ready=::poll(&input,1,10);if(ready>0&&(input.revents&POLLIN)){if(!std::getline(std::cin,line))break;if(line=="quit"||line=="exit")running=false;else if(line=="scan"){supervisor.send_discovery(now);std::cout<<"Discovery broadcast sent\n";}else if(line=="inventory")inventory(supervisor);else if(line=="monitor on"){monitor=true;std::cout<<"Packet monitor ON\n";}else if(line=="monitor off"){monitor=false;std::cout<<"Packet monitor OFF\n";}else if(line=="events")print_history(false);else if(line=="faults")print_history(true);else if(line=="clear"){history.clear();std::cout<<"Event history cleared\n";}else if(!line.empty())std::cout<<"Unknown command\n";if(running)std::cout<<"> "<<std::flush;}}return 0;}
