#include <chrono>
#include <cstdint>
#include <deque>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <poll.h>
#include <sstream>
#include <string>
#include "bike/lighting_diagnostics.hpp"
#include "bike/node.hpp"
#include "bike/security.hpp"
#include "bike/supervisor.hpp"
#include "posix_serial_transport.hpp"
namespace {
struct Event{std::uint32_t time_ms;bike::NodeAddress source;bike::MessageType type;std::string text;};std::deque<Event> history;constexpr std::size_t kHistoryLimit=250;std::ofstream logfile;bool monitor=true;bool filter_node_enabled=false;bike::NodeAddress filter_node=bike::NodeAddress::Broadcast;
std::uint32_t now_ms(){using namespace std::chrono;return static_cast<std::uint32_t>(duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count());}
const char* node_name(bike::NodeAddress a){switch(a){case bike::NodeAddress::MainComputer:return"MAIN";case bike::NodeAddress::DiagnosticComputer:return"DIAG";case bike::NodeAddress::Northbridge:return"NORTHBRIDGE";case bike::NodeAddress::Lighting:return"LIGHTING";case bike::NodeAddress::Security:return"SECURITY";case bike::NodeAddress::Broadcast:return"BROADCAST";}return"UNKNOWN";}
const char* type_name(bike::MessageType t){switch(t){case bike::MessageType::Heartbeat:return"HEARTBEAT";case bike::MessageType::Ack:return"ACK";case bike::MessageType::Nack:return"NACK";case bike::MessageType::GetState:return"GET_STATE";case bike::MessageType::StateUpdate:return"STATE_UPDATE";case bike::MessageType::SetOutput:return"SET_OUTPUT";case bike::MessageType::InputEvent:return"INPUT_EVENT";case bike::MessageType::LightingDiagnostic:return"LIGHTING_DIAGNOSTIC";case bike::MessageType::ConfigRead:return"CONFIG_READ";case bike::MessageType::ConfigWrite:return"CONFIG_WRITE";case bike::MessageType::Fault:return"FAULT";case bike::MessageType::FaultClear:return"FAULT_CLEAR";case bike::MessageType::DeviceInfo:return"DEVICE_INFO";case bike::MessageType::DeviceDiscovery:return"DEVICE_DISCOVERY";case bike::MessageType::Diagnostic:return"DIAGNOSTIC";case bike::MessageType::SecurityCommand:return"SECURITY_COMMAND";case bike::MessageType::SecurityState:return"SECURITY_STATE";case bike::MessageType::SecurityEvent:return"SECURITY_EVENT";case bike::MessageType::AuthRequest:return"AUTH_REQUEST";case bike::MessageType::AuthResult:return"AUTH_RESULT";case bike::MessageType::FobPresent:return"FOB_PRESENT";}return"UNKNOWN";}
const char* security_event(std::uint8_t e){switch(static_cast<bike::SecurityEventCode>(e)){case bike::SecurityEventCode::ShockWarning:return"SHOCK_WARNING";case bike::SecurityEventCode::ShockTrigger:return"SHOCK_TRIGGER";case bike::SecurityEventCode::AlarmStarted:return"ALARM_STARTED";case bike::SecurityEventCode::AlarmStopped:return"ALARM_STOPPED";case bike::SecurityEventCode::Locked:return"LOCKED";case bike::SecurityEventCode::Unlocked:return"UNLOCKED";case bike::SecurityEventCode::LockPending:return"LOCK_PENDING";}return"UNKNOWN_SECURITY_EVENT";}
const char* light_status(std::uint8_t s){switch(static_cast<bike::LightingElectricalStatus>(s)){case bike::LightingElectricalStatus::Unknown:return"UNKNOWN";case bike::LightingElectricalStatus::Off:return"OFF";case bike::LightingElectricalStatus::Ok:return"OK";case bike::LightingElectricalStatus::OpenLoad:return"OPEN_LOAD";case bike::LightingElectricalStatus::OverCurrent:return"OVER_CURRENT";}return"UNKNOWN";}
const char* light_output(std::uint8_t o){switch(o){case 0:return"LEFT_INDICATOR";case 1:return"RIGHT_INDICATOR";case 2:return"BRAKE_BRIGHT";case 3:return"HIGH_BEAM";}return"UNKNOWN_OUTPUT";}
const char* reset_reason(std::uint8_t r){switch(static_cast<bike::ResetReason>(r)){case bike::ResetReason::Unknown:return"UNKNOWN";case bike::ResetReason::PowerOn:return"POWER_ON";case bike::ResetReason::Software:return"SOFTWARE";case bike::ResetReason::Watchdog:return"WATCHDOG";case bike::ResetReason::Brownout:return"BROWNOUT";case bike::ResetReason::External:return"EXTERNAL";case bike::ResetReason::DeepSleep:return"DEEP_SLEEP";}return"UNKNOWN";}
const char* health(bike::NodeHealth h){switch(h){case bike::NodeHealth::Unknown:return"UNKNOWN";case bike::NodeHealth::Online:return"ONLINE";case bike::NodeHealth::Degraded:return"DEGRADED";case bike::NodeHealth::Offline:return"OFFLINE";case bike::NodeHealth::Incompatible:return"INCOMPATIBLE";}return"?";}
std::string hex_payload(const bike::Packet&p){std::ostringstream o;for(std::uint16_t i=0;i<p.length;++i){if(i)o<<' ';o<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(p.payload[i]);}return o.str();}
std::string decode(const bike::Packet&p){std::ostringstream o;o<<type_name(p.type);if(p.type==bike::MessageType::SecurityEvent&&p.length>=1)o<<" event="<<security_event(p.payload[0]);else if(p.type==bike::MessageType::SecurityState&&p.length>=6)o<<" mode="<<unsigned(p.payload[0])<<" inhibit="<<unsigned(p.payload[1])<<" alarm="<<unsigned(p.payload[2])<<" warning="<<unsigned(p.payload[3])<<" trigger="<<unsigned(p.payload[4])<<" engine="<<unsigned(p.payload[5]);else if(p.type==bike::MessageType::StateUpdate&&p.length>=4)o<<" left="<<unsigned(p.payload[0])<<" right="<<unsigned(p.payload[1])<<" brake="<<unsigned(p.payload[2])<<" high="<<unsigned(p.payload[3]);else if(p.type==bike::MessageType::LightingDiagnostic&&p.length>=24){for(int i=0;i<4;++i){int x=i*6;std::uint16_t ma=(std::uint16_t(p.payload[x+4])<<8)|p.payload[x+5];o<<" ["<<light_output(p.payload[x])<<' '<<light_status(p.payload[x+3])<<' '<<ma<<"mA]";}}else if(p.type==bike::MessageType::DeviceInfo&&p.length>=16){std::uint32_t up=(std::uint32_t(p.payload[10])<<24)|(std::uint32_t(p.payload[11])<<16)|(std::uint32_t(p.payload[12])<<8)|p.payload[13];o<<" protocol="<<unsigned(p.payload[3])<<" fw="<<unsigned(p.payload[4])<<'.'<<unsigned(p.payload[5])<<'.'<<unsigned(p.payload[6])<<" hw="<<unsigned(p.payload[7])<<" reset="<<reset_reason(p.payload[8])<<" uptime="<<up<<"ms";}else if(p.type==bike::MessageType::Fault&&p.source==bike::NodeAddress::Northbridge&&p.length>=5&&p.payload[0]==0x02&&p.payload[1]==0x01)o<<" TOPOLOGY_FAULT node=0x"<<std::hex<<unsigned(p.payload[2])<<std::dec<<" expected-port="<<unsigned(p.payload[3])<<" actual-port="<<unsigned(p.payload[4]);else if(p.length)o<<" payload=["<<hex_payload(p)<<']';return o.str();}
void remember(std::uint32_t t,const bike::Packet&p,const std::string&s){history.push_back({t,p.source,p.type,s});while(history.size()>kHistoryLimit)history.pop_front();if(logfile){logfile<<t<<','<<node_name(p.source)<<','<<node_name(p.destination)<<','<<type_name(p.type)<<','<<'"'<<s<<'"'<<'\n';logfile.flush();}}
bool visible(const bike::Packet&p){return !filter_node_enabled||p.source==filter_node||p.destination==filter_node;}
void packet_line(std::uint32_t t,const bike::Packet&p){if(!visible(p))return;std::cout<<'['<<t<<"] "<<node_name(p.source)<<" -> "<<node_name(p.destination)<<' '<<decode(p)<<" seq="<<p.sequence<<" len="<<p.length<<" flags=0x"<<std::hex<<unsigned(p.flags)<<std::dec<<'\n';}
void inventory(const bike::NetworkSupervisor&s){std::cout<<"NETWORK INVENTORY required-fault="<<(s.required_node_fault()?"YES":"NO")<<'\n';for(const auto&n:s.nodes()){if(!n.discovered)continue;std::cout<<node_name(n.address)<<" health="<<health(n.health)<<" required="<<(n.required?"yes":"no");if(n.identity_valid)std::cout<<" fw="<<unsigned(n.firmware_major)<<'.'<<unsigned(n.firmware_minor)<<'.'<<unsigned(n.firmware_patch)<<" proto="<<unsigned(n.protocol_version)<<" reset="<<reset_reason(static_cast<std::uint8_t>(n.reset_reason))<<" uptime="<<n.uptime_ms<<"ms reboots="<<n.reboot_count<<" faults="<<n.fault_count;std::cout<<'\n';}}
void print_history(bool faults){for(const auto&e:history){if(faults&&e.type!=bike::MessageType::Fault&&e.type!=bike::MessageType::FaultClear&&e.type!=bike::MessageType::LightingDiagnostic)continue;if(filter_node_enabled&&e.source!=filter_node)continue;std::cout<<'['<<e.time_ms<<"] "<<node_name(e.source)<<' '<<e.text<<'\n';}}
bool set_filter(const std::string&s){if(s=="off"){filter_node_enabled=false;return true;}filter_node_enabled=true;if(s=="northbridge")filter_node=bike::NodeAddress::Northbridge;else if(s=="lighting")filter_node=bike::NodeAddress::Lighting;else if(s=="security")filter_node=bike::NodeAddress::Security;else if(s=="main")filter_node=bike::NodeAddress::MainComputer;else{filter_node_enabled=false;return false;}return true;}
}
int main(int argc,char**argv){const std::string dev=argc>1?argv[1]:"/dev/serial0";PosixSerialTransport transport;if(!transport.open_device(dev,115200)){std::cerr<<"Unable to open "<<dev<<'\n';return 1;}logfile.open("motorcycle-diagnostics.csv",std::ios::app);if(logfile&&logfile.tellp()==0)logfile<<"time_ms,source,destination,type,decoded\n";bike::BikeNode node(bike::NodeAddress::DiagnosticComputer,transport);bike::NetworkSupervisor supervisor(node);supervisor.send_discovery(now_ms());std::cout<<"Motorcycle diagnostic computer on "<<dev<<"\nCommands: scan, inventory, monitor on|off, events, faults, filter off|northbridge|lighting|security|main, clear, quit\n> "<<std::flush;bool running=true;pollfd input{};input.fd=0;input.events=POLLIN;std::string line;while(running){auto now=now_ms();bike::Packet p{};while(node.poll(p,now)){supervisor.observe(p,now);auto text=decode(p);remember(now,p,text);if(monitor)packet_line(now,p);}supervisor.service(now);node.service(now);int ready=::poll(&input,1,10);if(ready>0&&(input.revents&POLLIN)){if(!std::getline(std::cin,line))break;if(line=="quit"||line=="exit")running=false;else if(line=="scan")supervisor.send_discovery(now);else if(line=="inventory")inventory(supervisor);else if(line=="monitor on")monitor=true;else if(line=="monitor off")monitor=false;else if(line=="events")print_history(false);else if(line=="faults")print_history(true);else if(line=="clear")history.clear();else if(line.rfind("filter ",0)==0){if(!set_filter(line.substr(7)))std::cout<<"Unknown filter\n";}else if(!line.empty())std::cout<<"Unknown command\n";if(running)std::cout<<"> "<<std::flush;}}return 0;}
