#include "self_test_runner.hpp"
namespace diag {
namespace { bool send(bike::BikeNode&n,bike::NodeAddress dst,bike::MessageType type,std::uint32_t now){bike::Packet p{};p.destination=dst;p.type=type;return n.send(p,now,false);} std::uint32_t u32(const std::uint8_t*p){return(std::uint32_t(p[0])<<24)|(std::uint32_t(p[1])<<16)|(std::uint32_t(p[2])<<8)|p[3];} }
void SelfTestRunner::begin(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(active_)return;index_=0;started_=now;total_elapsed_=0;report_ready_=false;active_=true;for(auto&i:items_){i.result=TestResult::Pending;i.started=0;i.elapsed=0;i.detail.clear();}start_next(n,s,now);}
void SelfTestRunner::start_next(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){while(index_<items_.size()){auto&i=items_[index_];const auto*st=s.status(i.node);if(!st||!st->online){i.result=TestResult::Fail;i.detail="offline";++index_;continue;}if(st->health==bike::NodeHealth::Incompatible){i.result=TestResult::Fail;i.detail="protocol incompatible";++index_;continue;}i.started=now;if(!send(n,i.node,i.request,now)){i.result=TestResult::Fail;i.detail="request send failed";++index_;continue;}return;}finish(now);}
void SelfTestRunner::observe(const bike::Packet&p,bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(!active_||index_>=items_.size())return;auto&i=items_[index_];if(p.source!=i.node||p.type!=i.response)return;i.elapsed=now-i.started;bool valid=true;if(i.node==bike::NodeAddress::Northbridge){valid=p.length>=18;if(valid&&u32(&p.payload[6])>0){i.result=TestResult::Warn;i.detail="dropped packets recorded";}else i.detail="routing diagnostics valid";}else if(i.node==bike::NodeAddress::Lighting){valid=p.length>=8;i.detail="lighting state received";}else{valid=p.length>=6;i.detail="security state received";}if(!valid){i.result=TestResult::Fail;i.detail="malformed response";}else if(i.result!=TestResult::Warn){const auto*st=s.status(i.node);i.result=(st&&st->health==bike::NodeHealth::Degraded)?TestResult::Warn:TestResult::Pass;if(i.result==TestResult::Warn)i.detail="response valid, node degraded";}++index_;start_next(n,s,now);}
void SelfTestRunner::service(bike::BikeNode&n,const bike::NetworkSupervisor&s,std::uint32_t now){if(!active_||index_>=items_.size())return;auto&i=items_[index_];if(now-i.started<=1000)return;i.result=TestResult::Fail;i.elapsed=now-i.started;i.detail="response timeout";++index_;start_next(n,s,now);}
void SelfTestRunner::finish(std::uint32_t now){active_=false;report_ready_=true;total_elapsed_=now-started_;}
} // namespace diag
